% [XTrain, YTrain] = japaneseVowelsTrainData;
% 
% layers = [
%     sequenceInputLayer(12) ...
%     lstmLayer(100, 'OutputMode', 'last') ...
%     fullyConnectedLayer(9) ...
%     softmaxLayer ...
%     classificationLayer ...
% ];
% options = trainingOptions('adam',...
%     'ExecutionEnvironment', 'cpu', ...
%     'MaxEpochs', 100, ...
%     'MiniBatchSize', 27, ...
%     'GradientThreshold', 1, ...
%     'Verbose', false, ...
%     'Plots', 'training-progress' ...
% );
% net = trainNetwork(XTrain, YTrain, layers, options);

%%

net = fitnet([3 12 12 12 4], 'trainbfg');
net = train(net, nnTrainInputs, nnTrainOutputs);
prediction = net(nnTrainInputs(:, 1));

%%

% layers = [
%     sequenceInputLayer(4) ...
%     lstmLayer(100, 'OutputMode', 'last') ...
%     fullyConnectedLayer(4) ...
%     softmaxLayer ...
% ];
% options = trainingOptions('adam',...
%     'ExecutionEnvironment', 'cpu', ...
%     'MaxEpochs', 100, ...
%     'MiniBatchSize', 27, ...
%     'GradientThreshold', 1, ...
%     'Verbose', false, ...
%     'Plots', 'training-progress' ...
% );
% net = trainNetwork(nnTrainInputs, nnTrainOutputs, layers, options);